//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UberScraper.Properties {
    using System.CodeDom.Compiler;
    using System.Configuration;
    using System.Diagnostics;
    using System.Drawing;
    using System.Runtime.CompilerServices;

    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("1")]
        public decimal numericThrottle {
            get {
                return ((decimal)(this["numericThrottle"]));
            }
            set {
                this["numericThrottle"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool checkedAIBrainDotOrg {
            get {
                return ((bool)(this["checkedAIBrainDotOrg"]));
            }
            set {
                this["checkedAIBrainDotOrg"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("100, 100")]
        public Point MainFormLocation {
            get {
                return ((Point)(this["MainFormLocation"]));
            }
            set {
                this["MainFormLocation"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool checkedBitChest {
            get {
                return ((bool)(this["checkedBitChest"]));
            }
            set {
                this["checkedBitChest"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool checkedLandOfBitcoin {
            get {
                return ((bool)(this["checkedLandOfBitcoin"]));
            }
            set {
                this["checkedLandOfBitcoin"] = value;
            }
        }
    }
}
